
###

GET http://localhost:3060/posts

###

GET http://localhost:3060/posts?owner=NoyAmsalem

###

GET http://localhost:3060/posts/6734b0c818a1cf8344804554

###


DELETE http://localhost:3060/posts/6734b0c818a1cf8344804554

### admin login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "admin2",
  "password": "admin123"
}

### create new user by admin
POST http://localhost:3000/auth/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyMzQ1Njc4OTAiLCJ1c2VybmFtZSI6ImFkbWluMiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0NDYyNjEzMSwiZXhwIjoxNzQ0NjI5NzMxfQ.UoTusmxaFBJFU3lZyfbRHrbyD4sXaETEdCGUf8d7BfM

{
  "id": "9876543211",
  "username": "employee3",
  "password": "1234567",
  "firstName": "David3",
  "lastName": "Gold3",
  "email": "david.gold3@company.com",
  "role": "user"
}



### login as employee1 (user)
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "employee1",
  "password": "1234"
}


### Start shift
POST http://localhost:3000/attendance/start
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk4NzY1NDMyMSIsInVzZXJuYW1lIjoiZW1wbG95ZWUxIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDQ0NzA5NjYsImV4cCI6MTc0NDQ3NDU2Nn0.cZkLkgDP7JIMcqoB07daGNoIjgCg0Ig0mznejtmg47U


### End shift
POST http://localhost:3000/attendance/end
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk4NzY1NDMyMSIsInVzZXJuYW1lIjoiZW1wbG95ZWUxIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDQ0NzA4MDEsImV4cCI6MTc0NDQ3NDQwMX0.duRZ-c-ttSWS5NdYaAsN4vPgSAJvaQZncsd99f7ANK4



### Edit attendance record by admin
PUT http://localhost:3000/attendance/edit/c31b13ac-028e-4468-81e8-e8633bd78017
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyMzQ1Njc4OSIsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDQ0NzE1NTQsImV4cCI6MTc0NDQ3NTE1NH0.GmN4KoG6igvEIwd1GiQ_OXJRhBUKhh-7OrJrf5PGDYY

{
  "type": "out",
  "timestamp": "2025-04-12T18:30:00"
}



### Admin Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "admin2",
  "password": "admin123"
}




### shift delete by admin
DELETE http://localhost:3000/attendance/delete/3b96d606-6cca-47fa-a6f2-81d46e9d2181
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyMzQ1Njc4OTAiLCJ1c2VybmFtZSI6ImFkbWluMiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0NDc0MDQwMSwiZXhwIjoxNzQ0NzQ0MDAxfQ.Fop9aZyRYZOnS2bkKlJlNjsmKXblSblGpV1hCOyMKoM


### shift edit by admin
PUT http://localhost:3000/attendance/edit/3b96d606-6cca-47fa-a6f2-81d46e9d2181
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyMzQ1Njc4OTAiLCJ1c2VybmFtZSI6ImFkbWluMiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0NDc0MDQwMSwiZXhwIjoxNzQ0NzQ0MDAxfQ.Fop9aZyRYZOnS2bkKlJlNjsmKXblSblGpV1hCOyMKoM

{
  "timestamp": "2025-04-15T09:00:00Z", 
  "type": "out"
}